project_name: toshiki-rssbot
env:
  - GO111MODULE=on
builds:
  - env:
      - CGO_ENABLED=0
    ldflags: -s -w -X github.com/andatoshiki/toshiki-rssbot/internal/config.version={{.Version}} -X github.com/andatoshiki/toshiki-rssbot/internal/config.date={{.Date}} -X github.com/andatoshiki/toshiki-rssbot/internal/config.commit={{ .ShortCommit }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
        - 6
        - 7
    ignore:
      - goos: linux
        goarch: amd64_v1
      - goos: windows
        goarch: arm
      - goos: linux
        goarch: arm_7
      - goos: darwin
        goarch: arm64
      - goos: darwin
        goarch: 386
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
archives:
  # - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  #   replacements:
  #     darwin: Darwin
  #     linux: Linux
  #     windows: Windows
  #     386: 32bit
  #     amd64: 64bit
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}64bit
      {{- else if eq .Arch "386" }}32bit
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip
    files:
      # - README.md
      - config.yml.sample
      - LICENSE
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  use: github
  sort: asc
  groups:
    - title: New Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 2
    - title: 'Refactoring'
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 3
    - title: Others
      order: 4
release:
  draft: true