project_name: toshiki-rssbot
env:
  - GO111MODULE=on
builds:
  - env:
      - CGO_ENABLED=0
    ldflags: -s -w -X github.com/andatoshiki/toshiki-rssbot/internal/config.version={{.Version}} -X github.com/andatoshiki/toshiki-rssbot/internal/config.date={{.Date}} -X github.com/andatoshiki/toshiki-rssbot/internal/config.commit={{ .ShortCommit }}
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - s390x
      - loong64
      - mips
      - mips64
    goarm:
      - 5
      - 6
      - 7
    goamd64:
      - v1
      - v2
      - v3
      - v4
checksum:
  name_template: '{{ .ProjectName }}-checksums.txt'
archives:
  - name_template: >-
      {{- .ProjectName }}-{{- title .Os }}-{{ .Arch }}-{{- if .Arm }}v{{ .Arm }}{{- else if .Amd64 }}{{ .Amd64 }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip
    files:
      # - README.md
      - config.yml.sample
      - LICENSE
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  use: github
  sort: asc
  groups:
    - title: New Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 2
    - title: 'Refactoring'
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 3
    - title: Others
      order: 4
release:
  draft: true