version: '3.4'

services:
  toshiki-rssbot:
    build:
      network: host
      context: .
      dockerfile: Dockerfile
    image: toshiki-rssbot
    volumes:
      - ./conf:/root/.toshiki-rssbot
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 1g
      restart_policy:
        condition: on-failure
