name: Build Docker images and publish to ghcr registry

on:
  push:
    branches:
      - master
    tags:
      - '*'
    # tags-ignore:
    #   - v*.*.*-dev
  pull_request:

jobs:
  build:
    name: Docker image build and publish
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/setup-buildx-action@v2
      - name: Check out code into the Go module directory
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: andatoshiki
          password: ${{ secrets.CR_PAT }}
      - name: Build and push Docker images
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64
          context: .
          tags: ghcr.io/andatoshiki/toshiki-e5subot:latest