name: Release V2

on:
  release:
    types: [created]
  workflow_dispatch:
  push:

jobs:
  linux-releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin, freebsd ]
        goarch: ["386", amd64, arm64, arm ]
        goarm: [5, 6, 7]
        exclude:
            - goarch: "386"
              goos: darwin
            - goarch: arm64
              goos: windows
            - goarch: arm
              goos: darwin

    steps:
      - uses: actions/checkout@v2
      
      - name: Set APP_VERSION env
        run: echo ::`echo -n name=APP_VERSION`::$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev )
      - name: Set BUILD_TIME env
        run: echo ::`echo -n name=BUILD_TIME`::$(date)
      - name: Environment Printer
        uses: managedkaos/print-env@v1.0

      - uses: wangyoucao577/go-release-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          extra_files: config.yml.sample LICENSE
          build_flags: -v
          ldflags: -X 'github.com/andatoshiki/toshiki-rssbot/internal/config.commit=${{ github.sha }}' -X 'github.com/andatoshiki/toshiki-rssbot/internal/config.date=${{ env.BUILD_TIME }}' -X 'github.com/andatoshiki/toshiki-rssbot/internal/config.version=${{ env.APP_VERSION }}'