name: Build and Release toshiki-rssbot V2

on:
  release:
    types: [created]

jobs:
  linux-releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
        matrix:
            goos: [windows, freebsd, openbsd, linux, darwin]
            goarch: [amd64, 386, arm64, arm]
            exclude:
              - goarch: 386
                goos: darwin
              - goarch: arm
                goos: darwin
    
              - goarch: arm
                goos: windows
              - goarch: 386
                goos: windows
    
              - goarch: arm
                goos: freebsd
              - goarch: 386
                goos: freebsd
    
              - goarch: arm
                goos: openbsd
              - goarch: 386
                goos: openbsd

    steps:
      - uses: actions/checkout@v2
      
      - name: Set APP_VERSION env
        run: echo ::`echo -n name=APP_VERSION`::$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev )
      - name: Set BUILD_TIME env
        run: echo ::`echo -n name=BUILD_TIME`::$(date)
      - name: Environment Printer
        uses: managedkaos/print-env@v1.0

      - uses: wangyoucao577/go-release-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          extra_files: config.yml.sample README.md
          build_flags: -v
          ldflags: -X 'github.com/andatoshiki/toshiki-rssbot/internal/config.commit=${{ github.sha }}' -X 'github.com/andatoshiki/toshiki-rssbot/internal/config.date=${{ env.BUILD_TIME }}' -X 'github.com/andatoshiki/toshiki-rssbot/internal/config.version=${{ env.APP_VERSION }}'