name: Build and Release toshiki-rssbot

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
        - 'master'
        - 'dev'
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set APP_VERSION env
        run: echo ::`echo -n name=APP_VERSION`::$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev )
      - name: Set BUILD_TIME env
        run: echo ::`echo -n name=BUILD_TIME`::$(date)
      - name: Environment Printer
        uses: managedkaos/print-env@v1.0
      - name: Fetch all tags
        run: git fetch --force --tags 
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: toshiki-e5subot
          path: ./dist/*